export const ProjectsData = [
    {
        id: 1,
        codeName: "wywrotkamcitemshop",
        name: "Minecraft ItemShop for WywrotkaMC",
        description: "Frontend and Backend of shop with dashboard",
        fullDescription: (<p>Soon</p>),
        imgURL: "/1/prev.png",
        fullImgURL: "/1/full.png",
        tags: ["Python", "Flask", "MongoDB", "MySQL", "HTML", "CSS", "JavaScript"],
    },
    {
        id: 2,
        codeName: "hotmcitemshop",
        name: "Minecraft ItemShop for HotMC",
        description: "Frontend and Backend of shop with dashboard",
        fullDescription: (<p>Soon</p>),
        imgURL: "/2/prev.png",
        fullImgURL: "/2/full.png",
        tags: ["Python", "Flask", "MongoDB", "HTML", "CSS", "JavaScript"],
    },
    {
        id: 3,
        codeName: "dropcms",
        name: "Multi Domain Shop with CMS system",
        description: "Frontend and Backend of shop with dashboard",
        fullDescription: (<p>Soon</p>),
        imgURL: "/3/prev.png",
        fullImgURL: "/3/full.png",
        tags: ["Python", "Flask", "MongoDB", "HTML", "CSS", "JavaScript", "React", "Bootstrap"],
    },
    {
        id: 4,
        codeName: "portfolio",
        name: "Portfolio site for me",
        description: "Frontend of site",
        fullDescription: (<p>Soon</p>),
        imgURL: "/4/prev.png",
        fullImgURL: "/3/full.png",
        tags: ["HTML", "CSS", "React", "TailwindCSS"],
    },
]